version: "3"

services:
  web-app-dev: &web-app-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_CONN_URI: postgresql+psycopg2://user:password@pg:5432/library
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    depends_on:
      - pg
#        condition: service_healthy

  web-app-prod:
    <<: *web-app-dev
    command: uwsgi
    environment:
      DB_CONN_URI: postgresql+psycopg2://user:password@pg:5432/library
      FLASK_ENV: production

  pg:
    image: postgres
    env_file:
      - postgres.env
    ports:
#      - "5432:5432"
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data: